# Generated by Django 4.0.4 on 2022-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('course_details', models.CharField(choices=[('Difficulty levels', (('easy', 'Easy'), ('medium', 'Intermediate'), ('hard', 'Hard'))), ('Course Type ', (('instructor-led', 'Instructor-Led'), ('on-demand', 'On-Demand'), ('both', 'Both'))), ('Lessons', (('1', 'Lesson one'), ('2', 'Lesson two'), ('3', 'Lesson three'))), ('Practical Assessment', (('assessment_one', 'Assessment-One'),))], max_length=50)),
                ('specialty', models.CharField(choices=[('Programming Languages', (('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript'))), ('Frameworks', (('java', 'Spring'), ('python', 'Django'), ('javascript', 'ReactJs')))], max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
