# Generated by Django 4.0.4 on 2022-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('course_details', models.CharField(choices=[('Difficulty levels', (('easy', 'Easy'), ('medium', 'Intermediate'), ('hard', 'Hard')))], max_length=50)),
                ('type_of_course', models.CharField(choices=[('Course Type ', (('instructor-led', 'Instructor-Led'), ('on-demand', 'On-Demand'), ('both', 'Both')))], max_length=50)),
                ('lessons_offered', models.CharField(choices=[('Lessons', (('1', 'Lesson one'), ('2', 'Lesson two'), ('3', 'Lesson three')))], max_length=50)),
                ('assessment', models.CharField(choices=[('Practical Assessment', (('assessment_one', 'Assessment-One'),))], max_length=50)),
                ('programming_languages', models.CharField(choices=[('Programming Languages', (('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript')))], max_length=50)),
                ('frameworks', models.CharField(choices=[('Frameworks', (('java', 'Spring'), ('python', 'Django'), ('javascript', 'ReactJs')))], max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Communities',
            new_name='Communitie',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
